=== ddmendes/SCC0661_Projeto1/curriculo.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<schema targetNamespace="http://www.example.com/curriculo" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:c="http://www.example.com/curriculo" elementFormDefault="qualified" attributeFormDefault="unqualified">

	

	<complexType name="creditsType">
		<sequence>
			<element name="aula"     type="integer" />
			<element name="trabalho" type="integer" />
		</sequence>
	</complexType>

	<simpleType name="categoryType">
		<restriction base="string">
			<enumeration value="obrigatória" />
			<enumeration value="eletiva"     />
		</restriction>
	</simpleType>

	<simpleType name="courseIdType">
		<restriction base="string">
			<pattern value="[A-Z]{3}\d{4}" />
		</restriction>
	</simpleType>

	<complexType name="courseType">
		<sequence>
			<element name="nome"      type="string"         />
			<element name="categoria" type="c:categoryType" />
			<element name="creditos"  type="c:creditsType"  />
		</sequence>
		<attribute name="id" type="c:courseIdType" />
	</complexType>

	<complexType name="periodType">
		<sequence>
			<element name="disciplina" type="c:courseType" maxOccurs="unbounded" />
		</sequence>
		<attribute name="id" use="required">
			<simpleType>
				<restriction base="integer">
					<minInclusive value="1"  />
					<maxInclusive value="10" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="classType">
		<sequence>
			<element name="nome" type="string" />
			<element name="periodo" type="c:periodType" maxOccurs="unbounded" />
		</sequence>
		<attribute name="id" use="required">
			<simpleType>
				<restriction base="integer">
					<minInclusive value="1" />
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="availableCoursesType">
		<sequence>
			<element name="curso" type="c:classType" maxOccurs="unbounded">
				<!--Mantém id dos períodos como único-->
				<unique name="periodId">
					<selector xpath="periodo" />
					<field xpath="@id" />
				</unique>
			</element>
		</sequence>
	</complexType>

	<simpleType name="frequencyType">
		<restriction base="decimal">
			<minInclusive value="0"   />
			<maxInclusive value="100" />
		</restriction>
	</simpleType>

	<simpleType name="gradeType">
		<restriction base="decimal">
			<minInclusive value="0"  />
			<maxInclusive value="10" />
		</restriction>
	</simpleType>

	<simpleType name="statusType">
		<restriction base="string">
			<enumeration value="aprovado"  />
			<enumeration value="reprovado" />
			<enumeration value="cursando"  />
			<enumeration value="trancado"  />
		</restriction>
	</simpleType>


	<complexType name="coursesTakenType">
		<sequence>
			<element name="frequencia" type="c:frequencyType" />
			<element name="nota" type="c:gradeType" />
		</sequence>
		<attribute name="ref" type="c:courseIdType" use="required"  />
		<attribute name="status" type="c:statusType" use="required" />
	</complexType>

	<complexType name="semesterType">
		<sequence>
			<element name="disciplina" type="c:coursesTakenType" maxOccurs="unbounded" />
		</sequence>
		<attribute name="id" type="positiveInteger" />
	</complexType>

	<simpleType name="studentIdType">
		<restriction base="string">
			<pattern value="\d+" />
		</restriction>
	</simpleType>

	<complexType name="studentType">
		<sequence>
			<element name="nome" type="string" />
			<element name="semestre" type="c:semesterType" maxOccurs="unbounded">
				
			</element>
		</sequence>
		<attribute name="id" type="c:studentIdType" use="required" />
	</complexType>

	<element name="curriculos">
		<complexType>
			<sequence>
				<element name="disciplinasDisponiveis" type="c:availableCoursesType" />
				<element name="aluno" type="c:studentType" maxOccurs="unbounded" />
			</sequence>
		</complexType>
		<!---->
		<unique name="studentId">
			<selector xpath="aluno" />
			<field xpath="@id" />
		</unique>
		<!--Mantém id de periodo/disciplinas como chave primária-->
		<key name="courseId">
			<selector xpath="disciplinasDisponiveis/curso/periodo/disciplina" />
			<field xpath="@id" />
		</key>
		<!--Mantém ref de semestre/disciplina como chave estrangeira-->
		<keyref name="courseReference" refer="c:courseId">
			<selector xpath="aluno/semestre/disciplina" />
			<field xpath="@ref" />
		</keyref>
	</element>

</schema>

=== ddmendes/SCC0661_Projeto1/curriculos.xml
<?xml version="1.0" encoding="UTF-8"?>
<curriculos xmlns="http://www.example.com/curriculo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="curriculo curriculo.xsd">
	<disciplinasDisponiveis>
		<curso id="97001">
			<nome>Engenharia de Computação</nome>
			<periodo id="1">
				<disciplina id="FCM0101">
					<nome>Física I</nome>
					<categoria>obrigatória</categoria>
					<creditos>
						<aula>6</aula>
						<trabalho>0</trabalho>
					</creditos>
				</disciplina>
				<disciplina id="FFI0180">
					<nome>Laboratório de Física Geral I</nome>
					<categoria>obrigatória</categoria>
					<creditos>
						<aula>2</aula>
						<trabalho>0</trabalho>
					</creditos>
				</disciplina>
				<disciplina id="IAU0126">
					<nome>Humanidades e Ciências Sociais</nome>
					<categoria>obrigatória</categoria>
					<creditos>
						<aula>2</aula>
						<trabalho>0</trabalho>
					</creditos>
				</disciplina>
				<disciplina id="SEL0600">
					<nome>Informação Profissional em Engenharia de Computação I</nome>
					<categoria>obrigatória</categoria>
					<creditos>
						<aula>1</aula>
						<trabalho>0</trabalho>
					</creditos>
				</disciplina>
				<disciplina id="SMA0300">
					<nome>Geometria Analítica</nome>
					<categoria>obrigatória</categoria>
					<creditos>
						<aula>4</aula>
						<trabalho>0</trabalho>
					</creditos>
				</disciplina>
				<disciplina id="SMA0301">
					<nome>Cálculo I</nome>
					<categoria>obrigatória</categoria>
					<creditos>
						<aula>6</aula>
						<trabalho>0</trabalho>
					</creditos>
				</disciplina>
				<disciplina id="SSC0600">
					<nome>Introdução à Ciência da Computação I</nome>
					<categoria>obrigatória</categoria>
					<creditos>
						<aula>4</aula>
						<trabalho>0</trabalho>
					</creditos>
				</disciplina>
				<disciplina id="SSC0601">
					<nome>Laboratório de Introdução à Ciência da Computação I</nome>
					<categoria>obrigatória</categoria>
					<creditos>
						<aula>2</aula>
						<trabalho>2</trabalho>
					</creditos>
				</disciplina>
				<disciplina id="SSC0671">
					<nome>Informação Profissional em Engenharia da Computação II</nome>
					<categoria>obrigatória</categoria>
					<creditos>
						<aula>1</aula>
						<trabalho>0</trabalho>
					</creditos>
				</disciplina>
				<disciplina id="SSC0530">
					<nome>Introdução à Sistemas de Informação</nome>
					<categoria>eletiva</categoria>
					<creditos>
						<aula>2</aula>
						<trabalho>0</trabalho>
					</creditos>
				</disciplina>
			</periodo>
		</curso>
	</disciplinasDisponiveis>
	<aluno id="7526989">
		<nome>Davi Diório Mendes</nome>
		<semestre id="1">
			<disciplina ref="FCM0101" status="aprovado">
				<frequencia>100</frequencia>
				<nota>5.9</nota>
			</disciplina>
			<disciplina ref="FFI0180" status="aprovado">
				<frequencia>100</frequencia>
				<nota>9.0</nota>
			</disciplina>
			<disciplina ref="IAU0126" status="aprovado">
				<frequencia>100</frequencia>
				<nota>9.0</nota>
			</disciplina>
			<disciplina ref="SEL0600" status="aprovado">
				<frequencia>93</frequencia>
				<nota>10.0</nota>
			</disciplina>
			<disciplina ref="SMA0300" status="aprovado">
				<frequencia>100</frequencia>
				<nota>8.5</nota>
			</disciplina>
			<disciplina ref="SMA0301" status="aprovado">
				<frequencia>100</frequencia>
				<nota>6.1</nota>
			</disciplina>
			<disciplina ref="SSC0600" status="aprovado">
				<frequencia>100</frequencia>
				<nota>9.4</nota>
			</disciplina>
			<disciplina ref="SSC0601" status="aprovado">
				<frequencia>88</frequencia>
				<nota>9.8</nota>
			</disciplina>
			<disciplina ref="SSC0671" status="aprovado">
				<frequencia>100</frequencia>
				<nota>7.4</nota>
			</disciplina>
		</semestre>
	</aluno>
</curriculos>

=== ddmendes/SCC0661_Projeto1/curriculos2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<c:curriculos xmlns:c="http://www.example.com/curriculo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="curriculo curriculo.xsd">
	<c:disciplinasDisponiveis>
		<c:curso id="97001">
			<c:nome>Engenharia de Computação</c:nome>
			<c:periodo id="1">
				<c:disciplina id="FCM0101">
					<c:nome>Física I</c:nome>
					<c:categoria>obrigatória</c:categoria>
					<c:creditos>
						<c:aula>6</c:aula>
						<c:trabalho>0</c:trabalho>
					</c:creditos>
				</c:disciplina>
				<c:disciplina id="FFI0180">
					<c:nome>Laboratório de Física Geral I</c:nome>
					<c:categoria>obrigatória</c:categoria>
					<c:creditos>
						<c:aula>2</c:aula>
						<c:trabalho>0</c:trabalho>
					</c:creditos>
				</c:disciplina>
				<c:disciplina id="IAU0126">
					<c:nome>Humanidades e Ciências Sociais</c:nome>
					<c:categoria>obrigatória</c:categoria>
					<c:creditos>
						<c:aula>2</c:aula>
						<c:trabalho>0</c:trabalho>
					</c:creditos>
				</c:disciplina>
				<c:disciplina id="SEL0600">
					<c:nome>Informação Profissional em Engenharia de Computação I</c:nome>
					<c:categoria>obrigatória</c:categoria>
					<c:creditos>
						<c:aula>1</c:aula>
						<c:trabalho>0</c:trabalho>
					</c:creditos>
				</c:disciplina>
				<c:disciplina id="SMA0300">
					<c:nome>Geometria Analítica</c:nome>
					<c:categoria>obrigatória</c:categoria>
					<c:creditos>
						<c:aula>4</c:aula>
						<c:trabalho>0</c:trabalho>
					</c:creditos>
				</c:disciplina>
				<c:disciplina id="SMA0301">
					<c:nome>Cálculo I</c:nome>
					<c:categoria>obrigatória</c:categoria>
					<c:creditos>
						<c:aula>6</c:aula>
						<c:trabalho>0</c:trabalho>
					</c:creditos>
				</c:disciplina>
				<c:disciplina id="SSC0600">
					<c:nome>Introdução à Ciência da Computação I</c:nome>
					<c:categoria>obrigatória</c:categoria>
					<c:creditos>
						<c:aula>4</c:aula>
						<c:trabalho>0</c:trabalho>
					</c:creditos>
				</c:disciplina>
				<c:disciplina id="SSC0601">
					<c:nome>Laboratório de Introdução à Ciência da Computação I</c:nome>
					<c:categoria>obrigatória</c:categoria>
					<c:creditos>
						<c:aula>2</c:aula>
						<c:trabalho>2</c:trabalho>
					</c:creditos>
				</c:disciplina>
				<c:disciplina id="SSC0671">
					<c:nome>Informação Profissional em Engenharia da Computação II</c:nome>
					<c:categoria>obrigatória</c:categoria>
					<c:creditos>
						<c:aula>1</c:aula>
						<c:trabalho>0</c:trabalho>
					</c:creditos>
				</c:disciplina>
				<c:disciplina id="SSC0530">
					<c:nome>Introdução à Sistemas de Informação</c:nome>
					<c:categoria>eletiva</c:categoria>
					<c:creditos>
						<c:aula>2</c:aula>
						<c:trabalho>0</c:trabalho>
					</c:creditos>
				</c:disciplina>
			</c:periodo>
			<c:periodo id="2">
				<c:disciplina id="FCM0102">
					<c:nome>Física II</c:nome>
					<c:categoria>eletiva</c:categoria>
					<c:creditos>
						<c:aula>6</c:aula>
						<c:trabalho>0</c:trabalho>
					</c:creditos>
				</c:disciplina>
			</c:periodo>
		</c:curso>
	</c:disciplinasDisponiveis>
	<c:aluno id="7526989">
		<c:nome>Davi Diório Mendes</c:nome>
		<c:semestre id="1">
			<c:disciplina ref="FCM0101" status="aprovado">
				<c:frequencia>100</c:frequencia>
				<c:nota>5.9</c:nota>
			</c:disciplina>
			<c:disciplina ref="FFI0180" status="aprovado">
				<c:frequencia>100</c:frequencia>
				<c:nota>9.0</c:nota>
			</c:disciplina>
			<c:disciplina ref="IAU0126" status="aprovado">
				<c:frequencia>100</c:frequencia>
				<c:nota>9.0</c:nota>
			</c:disciplina>
			<c:disciplina ref="SEL0600" status="aprovado">
				<c:frequencia>93</c:frequencia>
				<c:nota>10.0</c:nota>
			</c:disciplina>
			<c:disciplina ref="SMA0300" status="aprovado">
				<c:frequencia>100</c:frequencia>
				<c:nota>8.5</c:nota>
			</c:disciplina>
			<c:disciplina ref="SMA0301" status="aprovado">
				<c:frequencia>100</c:frequencia>
				<c:nota>6.1</c:nota>
			</c:disciplina>
			<c:disciplina ref="SSC0600" status="aprovado">
				<c:frequencia>100</c:frequencia>
				<c:nota>9.4</c:nota>
			</c:disciplina>
			<c:disciplina ref="SSC0601" status="aprovado">
				<c:frequencia>88</c:frequencia>
				<c:nota>9.8</c:nota>
			</c:disciplina>
			<c:disciplina ref="SSC0671" status="aprovado">
				<c:frequencia>100</c:frequencia>
				<c:nota>7.4</c:nota>
			</c:disciplina>
		</c:semestre>
	</c:aluno>
	<aluno id="7017647">
		<nome>João da Silva</nome>
	</aluno>
	<aluno id="7674521">
		<nome>Juca Mun Dongo</nome>
	</aluno>
	<aluno id="686875">
		<nome>Elise Gobbo</nome>
	</aluno>
</c:curriculos>
